### PR TITLE
Fix sidebars not scrollable

### LINKED ISSUE #34: Sidebars not scrollable: Need to scroll the entire page to see bottom of them
## Description

The sidebars don't have scrolls so if they are bigger than the screen, we need to scroll the entire page to see its end.

### Expected behavior

We can scroll to see any item on the sidebars without needing to scroll the page.

### Actual behavior

We need to scroll the entire page to see the last items of big sidebar menus.

https://user-images.githubusercontent.com/38889364/104638517-076aa200-5685-11eb-89e2-a204f9c4dc25.mp4

### PR DESCRIPTION
**Pull request by paulocfjunior**
Fixes #34 and https://github.com/traefik/doc/issues/259

https://user-images.githubusercontent.com/38889364/105188003-3021ea00-5b12-11eb-94c6-85fef510966a.mp4

### CODE REVIEW

**Review by matthieuh — CHANGES_REQUESTED** [review]
Search is not working anymore after those changes

**Comment by paulocfjunior** [comment]
It should be working now, even though I used a workaround on the HTML because it was taking too much time trying to solve on the JS side. If you have any ideas just let me know.

**Review by matthieuh — CHANGES_REQUESTED** [review]
Search is off on a desktop screen.

Screen Shot 2021-01-27 at 14 04 08

**Comment by paulocfjunior** [comment]
@matthieuh should be good now

**Review by matthieuh — APPROVED** [review]
LGTM

**Comment by matthieuh** [comment]
@paulocfjunior could you rebase your branch to the `main` one?

**Pull request merged**
